services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: attendance-management-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance_management
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - attendance-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: attendance-management-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - attendance-network

  # Laravel Backend (PHP-FPM)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: attendance-management-backend
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_REVALIDATE_FREQ=0
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=10000
      - PHP_OPCACHE_MEMORY_CONSUMPTION=192
      - PHP_OPCACHE_MAX_WASTED_PERCENTAGE=10
    volumes:
      - .:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - storage_data:/var/www/html/storage
      - bootstrap_cache:/var/www/html/bootstrap/cache
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - attendance-network

  # NGINX Web Server
  nginx:
    image: nginx:alpine
    container_name: attendance-management-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - attendance-network

  # Vite Development Server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: attendance-management-frontend
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - '5173:5173'
    volumes:
      - .:/var/www/html
      - frontend_node_modules:/var/www/html/node_modules
    environment:
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=5173
    depends_on:
      - backend
    networks:
      - attendance-network

networks:
  attendance-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  storage_data:
    driver: local
  bootstrap_cache:
    driver: local
  frontend_node_modules:
    driver: local
